const mongoose = require("mongoose");
const Menu = require("./models/Menu"); // Assuming your Menu model is in './models/Menu.js'
const dotenv = require("dotenv");

dotenv.config();

const dbURL = process.env.MONGO_URL;

const menuData = [
  // SOOPS - Indian
  {
    item_id: "S001",
    item_name: "Tomato Cream Soup",
    item_cty: "Soups",
    item_subcty: "Indian",
    item_price: 75,
    isveg: true,
    availability: true,
    item_img: "placeholder_soup.jpg", // Replace with actual image path if available
  },
  {
    item_id: "S002",
    item_name: "Veg Clear Soup",
    item_cty: "Soups",
    item_subcty: "Indian",
    item_price: 70,
    isveg: true,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  {
    item_id: "S003",
    item_name: "Creamy Chicken Soup",
    item_cty: "Soups",
    item_subcty: "Indian",
    item_price: 90,
    isveg: false,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  {
    item_id: "S004",
    item_name: "Spicy Chicken Soup",
    item_cty: "Soups",
    item_subcty: "Indian",
    item_price: 90,
    isveg: false,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  // SOOPS - Chinese
  {
    item_id: "S005",
    item_name: "Veg Manchow Soup",
    item_cty: "Soups",
    item_subcty: "Chinese",
    item_price: 70,
    isveg: true,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  {
    item_id: "S006",
    item_name: "Veg Sweet Corn Soup",
    item_cty: "Soups",
    item_subcty: "Chinese",
    item_price: 70,
    isveg: true,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  {
    item_id: "S007",
    item_name: "Veg Hot & Sour Soup",
    item_cty: "Soups",
    item_subcty: "Chinese",
    item_price: 70,
    isveg: true,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  {
    item_id: "S008",
    item_name: "Chicken Manchow Soup",
    item_cty: "Soups",
    item_subcty: "Chinese",
    item_price: 90,
    isveg: false,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  {
    item_id: "S009",
    item_name: "Chicken Sweet Corn Soup",
    item_cty: "Soups",
    item_subcty: "Chinese",
    item_price: 100,
    isveg: false,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  // SOOPS - Continental
  {
    item_id: "S010",
    item_name: "Veg Cream Mushroom Soup",
    item_cty: "Soups",
    item_subcty: "Continental",
    item_price: 75,
    isveg: true,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  {
    item_id: "S011",
    item_name: "Chicken Coriander Soup",
    item_cty: "Soups",
    item_subcty: "Continental",
    item_price: 130,
    isveg: false,
    availability: true,
    item_img: "placeholder_soup.jpg",
  },
  // STARTERS - Indian
  {
    item_id: "ST001",
    item_name: "Assorted Pakoda (Mix Veg/Onion)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 90,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST002",
    item_name: "Onion Pakoda",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST003",
    item_name: "Paneer Banjara Kebab (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 200,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST004",
    item_name: "Harabhara Kebab (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 140,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST005",
    item_name: "Paneer Tikka (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 175,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST006",
    item_name: "Paneer Malai Tikka (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 180,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST007",
    item_name: "Mushroom Tikka (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 155,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST008",
    item_name: "Soya Chaap (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  // STARTERS - Indian
  {
    item_id: "ST009",
    item_name: "Tandoori Chicken (half)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 310,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST010",
    item_name: "Tandoori Chicken (full)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 530,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST011",
    item_name: "Chicken Hariyali Kebab (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 180,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST012",
    item_name: "Chicken Reshmi Kebab (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 170,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST013",
    item_name: "Chicken Pahadi Kebab (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 175,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST014",
    item_name: "Chicken Achari Kebab (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 180,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST015",
    item_name: "Chicken Malai Tikka (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 175,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST016",
    item_name: "Tandoori Chicken Tikka (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 175,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST017",
    item_name: "Fish Tikka (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 180,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST018",
    item_name: "Fish Finger (6pcs)",
    item_cty: "Starters",
    item_subcty: "Indian",
    item_price: 220,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  // STARTERS - Chinese
  {
    item_id: "ST019",
    item_name: "Veg Manchurian (6pcs)",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 110,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST020",
    item_name: "Gobi Manchurian (6pcs)",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 155,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST021",
    item_name: "Paneer Chilli (6pcs)",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 170,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST022",
    item_name: "Mushroom Chilli (6pcs)",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 180,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST023",
    item_name: "Paneer 65 (6pcs)",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 180,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST024",
    item_name: "Veg Crispy",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 120,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST025",
    item_name: "Veg Momos",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 90,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  // STARTERS - Chinese
  {
    item_id: "ST026",
    item_name: "Chicken Lollipop (6pcs)",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 145,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST027",
    item_name: "Chicken Manchurian (6pcs)",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 175,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST028",
    item_name: "Chicken Chilli (6pcs)",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 175,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST029",
    item_name: "Chicken Hot Garlic (6pcs)",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 175,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST030",
    item_name: "Chicken Crispy",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 175,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST031",
    item_name: "Chicken Salt n Pepper",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 175,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST032",
    item_name: "Chicken Momos",
    item_cty: "Starters",
    item_subcty: "Chinese",
    item_price: 100,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  // STARTERS - Continental
  {
    item_id: "ST033",
    item_name: "Filter Baby Corn",
    item_cty: "Starters",
    item_subcty: "Continental",
    item_price: 180,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST034",
    item_name: "Stuffed Mushroom (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Continental",
    item_price: 200,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST035",
    item_name: "Paneer Shashlik (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Continental",
    item_price: 225,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST036",
    item_name: "Garlic Butter Grilled Paneer",
    item_cty: "Starters",
    item_subcty: "Continental",
    item_price: 250,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST037",
    item_name: "Paneer Sauté (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Continental",
    item_price: 200,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  // STARTERS - Continental
  {
    item_id: "ST038",
    item_name: "Chicken Cheese Corn Balls (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Continental",
    item_price: 225,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST039",
    item_name: "Grilled Fish (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Continental",
    item_price: 250,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST040",
    item_name: "Pepper Grilled Chicken (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Continental",
    item_price: 250,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST041",
    item_name: "Chicken Cutlet (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Continental",
    item_price: 200,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  // STARTERS - Frozen
  {
    item_id: "ST042",
    item_name: "French Fries",
    item_cty: "Starters",
    item_subcty: "Frozen",
    item_price: 80,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST043",
    item_name: "Veg Nuggets (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Frozen",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST044",
    item_name: "Desi Kebab (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Frozen",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST045",
    item_name: "Smileys (8 pcs)",
    item_cty: "Starters",
    item_subcty: "Frozen",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  // STARTERS - Frozen
  {
    item_id: "ST046",
    item_name: "Chicken Popcorn",
    item_cty: "Starters",
    item_subcty: "Frozen",
    item_price: 160,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST047",
    item_name: "Chicken Nuggets (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Frozen",
    item_price: 190,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST048",
    item_name: "Chicken Sausage (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Frozen",
    item_price: 190,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  {
    item_id: "ST049",
    item_name: "Chicken Seekh Kebab (6 pcs)",
    item_cty: "Starters",
    item_subcty: "Frozen",
    item_price: 200,
    isveg: false,
    availability: true,
    item_img: "placeholder_starter.jpg",
  },
  // Quick Bites - Veg
  {
    item_id: "QB001",
    item_name: "Wafers",
    item_cty: "Quick Bites",
    item_subcty: "Wafers",
    item_price: 40,
    isveg: true,
    availability: true,
    item_img: "placeholder_quickbite.jpg",
  },
  {
    item_id: "QB002",
    item_name: "Masala Peanuts (100gm)",
    item_cty: "Quick Bites",
    item_subcty: "Peanuts",
    item_price: 60,
    isveg: true,
    availability: true,
    item_img: "placeholder_quickbite.jpg",
  },
  {
    item_id: "QB003",
    item_name: "Salted Peanuts (100gm)",
    item_cty: "Quick Bites",
    item_subcty: "Peanuts",
    item_price: 60,
    isveg: true,
    availability: true,
    item_img: "placeholder_quickbite.jpg",
  },
  // MAIN COURSE - Indian
  {
    item_id: "MC001",
    item_name: "Dal Fry/Tadka",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 140,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC002",
    item_name: "Dal Makhani",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 220,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC003",
    item_name: "Aloo Mutter",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC004",
    item_name: "Mix Veg",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 180,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC005",
    item_name: "Veg Kolhapuri",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 175,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC006",
    item_name: "Veg Handi",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 190,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC007",
    item_name: "Mushroom Masala",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 180,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC008",
    item_name: "Mutter Paneer (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 190,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC009",
    item_name: "Paneer Kadai (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 175,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC010",
    item_name: "Paneer Butter Masala (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 190,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC011",
    item_name: "Paneer Tikka Masala (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 190,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC012",
    item_name: "Paneer Lababdar (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 240,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC013",
    item_name: "Malai Kofta (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 170,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  // MAIN COURSE - Indian
  {
    item_id: "MC014",
    item_name: "Butter Chicken (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 220,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC015",
    item_name: "Chicken Kolhapuri (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 210,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC016",
    item_name: "Chicken Do Pyaza (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 210,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC017",
    item_name: "Chicken Tikka Masala (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 220,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  {
    item_id: "MC018",
    item_name: "Chicken Kadai (6pcs)",
    item_cty: "Main Course",
    item_subcty: "Indian",
    item_price: 210,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse.jpg",
  },
  // Accompaniments
  {
    item_id: "AC001",
    item_name: "Papad Roasted",
    item_cty: "Accompaniments",
    item_subcty: "Indian",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_accompaniment.jpg",
  },
  {
    item_id: "AC002",
    item_name: "Fried Papad",
    item_cty: "Accompaniments",
    item_subcty: "Indian",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_accompaniment.jpg",
  },
  {
    item_id: "AC003",
    item_name: "Papad Masala",
    item_cty: "Accompaniments",
    item_subcty: "Indian",
    item_price: 30,
    isveg: true,
    availability: true,
    item_img: "placeholder_accompaniment.jpg",
  },
  {
    item_id: "AC004",
    item_name: "Green Salad",
    item_cty: "Accompaniments",
    item_subcty: "Indian",
    item_price: 50,
    isveg: true,
    availability: true,
    item_img: "placeholder_accompaniment.jpg",
  },
  {
    item_id: "AC005",
    item_name: "Pineapple Raita",
    item_cty: "Accompaniments",
    item_subcty: "Indian",
    item_price: 70,
    isveg: true,
    availability: true,
    item_img: "placeholder_accompaniment.jpg",
  },
  {
    item_id: "AC006",
    item_name: "Veg Raita",
    item_cty: "Accompaniments",
    item_subcty: "Indian",
    item_price: 60,
    isveg: true,
    availability: true,
    item_img: "placeholder_accompaniment.jpg",
  },
  {
    item_id: "AC007",
    item_name: "Boondi Raita",
    item_cty: "Accompaniments",
    item_subcty: "Indian",
    item_price: 60,
    isveg: true,
    availability: true,
    item_img: "placeholder_accompaniment.jpg",
  },
  {
    item_id: "AC008",
    item_name: "Curd",
    item_cty: "Accompaniments",
    item_subcty: "Indian",
    item_price: 50,
    isveg: true,
    availability: true,
    item_img: "placeholder_accompaniment.jpg",
  },
  // Rice
  {
    item_id: "RC001",
    item_name: "Plain Rice",
    item_cty: "Rice",
    item_subcty: "Indian",
    item_price: 65,
    isveg: true,
    availability: true,
    item_img: "placeholder_rice.jpg",
  },
  {
    item_id: "RC002",
    item_name: "Jeera Rice",
    item_cty: "Rice",
    item_subcty: "Indian",
    item_price: 85,
    isveg: true,
    availability: true,
    item_img: "placeholder_rice.jpg",
  },
  {
    item_id: "RC003",
    item_name: "Veg Pulao",
    item_cty: "Rice",
    item_subcty: "Indian",
    item_price: 115,
    isveg: true,
    availability: true,
    item_img: "placeholder_rice.jpg",
  },
  {
    item_id: "RC004",
    item_name: "Dal Khichdi",
    item_cty: "Rice",
    item_subcty: "Indian",
    item_price: 170,
    isveg: true,
    availability: true,
    item_img: "placeholder_rice.jpg",
  },
  {
    item_id: "RC005",
    item_name: "Veg Dum Biryani",
    item_cty: "Rice",
    item_subcty: "Indian",
    item_price: 195,
    isveg: true,
    availability: true,
    item_img: "placeholder_rice.jpg",
  },
  {
    item_id: "RC006",
    item_name: "Chicken Dum Biryani",
    item_cty: "Rice",
    item_subcty: "Indian",
    item_price: 235,
    isveg: false,
    availability: true,
    item_img: "placeholder_rice.jpg",
  },
  // Roti
  {
    item_id: "RT001",
    item_name: "Tandoori Roti",
    item_cty: "Roti",
    item_subcty: "Indian",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_roti.jpg",
  },
  {
    item_id: "RT002",
    item_name: "Tandoori Butter Roti",
    item_cty: "Roti",
    item_subcty: "Indian",
    item_price: 30,
    isveg: true,
    availability: true,
    item_img: "placeholder_roti.jpg",
  },
  {
    item_id: "RT003",
    item_name: "Naan",
    item_cty: "Roti",
    item_subcty: "Indian",
    item_price: 30,
    isveg: true,
    availability: true,
    item_img: "placeholder_roti.jpg",
  },
  {
    item_id: "RT004",
    item_name: "Butter Naan",
    item_cty: "Roti",
    item_subcty: "Indian",
    item_price: 40,
    isveg: true,
    availability: true,
    item_img: "placeholder_roti.jpg",
  },
  {
    item_id: "RT005",
    item_name: "Garlic Naan",
    item_cty: "Roti",
    item_subcty: "Indian",
    item_price: 30,
    isveg: true,
    availability: true,
    item_img: "placeholder_roti.jpg",
  },
  {
    item_id: "RT006",
    item_name: "Garlic Butter Naan",
    item_cty: "Roti",
    item_subcty: "Indian",
    item_price: 40,
    isveg: true,
    availability: true,
    item_img: "placeholder_roti.jpg",
  },
  {
    item_id: "RT007",
    item_name: "Lachha Paratha",
    item_cty: "Roti",
    item_subcty: "Indian",
    item_price: 40,
    isveg: true,
    availability: true,
    item_img: "placeholder_roti.jpg",
  },
  {
    item_id: "RT008",
    item_name: "Butter Kulcha",
    item_cty: "Roti",
    item_subcty: "Indian",
    item_price: 40,
    isveg: true,
    availability: true,
    item_img: "placeholder_roti.jpg",
  },
  // MAIN COURSE - Chinese
  {
    item_id: "MC019",
    item_name: "Veg Fried Rice",
    item_cty: "Main Course",
    item_subcty: "Chinese",
    item_price: 135,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  {
    item_id: "MC020",
    item_name: "Veg Schezwan Rice",
    item_cty: "Main Course",
    item_subcty: "Chinese",
    item_price: 160,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  {
    item_id: "MC021",
    item_name: "Veg Hakka Noodles",
    item_cty: "Main Course",
    item_subcty: "Chinese",
    item_price: 135,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  {
    item_id: "MC022",
    item_name: "Veg Manchurian (Gravy)", // Assuming this is gravy version for main course
    item_cty: "Main Course",
    item_subcty: "Chinese",
    item_price: 180,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  {
    item_id: "MC023",
    item_name: "Thai Curry Veg",
    item_cty: "Main Course",
    item_subcty: "Chinese", // PDF lists Thai Curry under Chinese Main Course
    item_price: 180,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  // MAIN COURSE - Chinese
  {
    item_id: "MC024",
    item_name: "Chicken Fried Rice",
    item_cty: "Main Course",
    item_subcty: "Chinese",
    item_price: 160,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  {
    item_id: "MC025",
    item_name: "Chicken Schezwan Rice",
    item_cty: "Main Course",
    item_subcty: "Chinese",
    item_price: 185,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  {
    item_id: "MC026",
    item_name: "Chicken Hakka Noodles",
    item_cty: "Main Course",
    item_subcty: "Chinese",
    item_price: 195,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  {
    item_id: "MC027",
    item_name: "Chicken Schezwan Noodles",
    item_cty: "Main Course",
    item_subcty: "Chinese",
    item_price: 195,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  {
    item_id: "MC028",
    item_name: "Chicken Manchurian (Gravy)", // Assuming this is gravy version for main course
    item_cty: "Main Course",
    item_subcty: "Chinese",
    item_price: 195,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse_chinese.jpg",
  },
  // MAIN COURSE - Continental
  {
    item_id: "MC029",
    item_name: "Garlic Brown Sauce Paneer",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 200,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC030",
    item_name: "Veg Stuffed Fry",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC031",
    item_name: "Baked Beans",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC032",
    item_name: "Spinach Corn",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC033",
    item_name: "Grilled Veg",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC034",
    item_name: "Cheese Cutlet",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC035",
    item_name: "Pepper Cutlet",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC036",
    item_name: "Veg Alfredo Pasta",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC037",
    item_name: "Veg Arrabiata Pasta",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  // MAIN COURSE - Continental
  {
    item_id: "MC038",
    item_name: "Garlic Brown Sauce Chicken",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 250,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC039",
    item_name: "Chicken Alfredo Pasta",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 225,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC040",
    item_name: "Chicken Arrabiata Pasta",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 225,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  {
    item_id: "MC041",
    item_name: "Chicken Pesto Pasta",
    item_cty: "Main Course",
    item_subcty: "Continental",
    item_price: 225,
    isveg: false,
    availability: true,
    item_img: "placeholder_maincourse_continental.jpg",
  },
  // Sizzlers - Veg
  {
    item_id: "SZ001",
    item_name: "Veg Chinese Sizzler",
    item_cty: "Sizzlers",
    item_subcty: "Chinese",
    item_price: 300,
    isveg: true,
    availability: true,
    item_img: "placeholder_sizzler.jpg",
  },
  {
    item_id: "SZ002",
    item_name: "Veg Continental Sizzler",
    item_cty: "Sizzlers",
    item_subcty: "Continental",
    item_price: 300,
    isveg: true,
    availability: true,
    item_img: "placeholder_sizzler.jpg",
  },
  {
    item_id: "SZ003",
    item_name: "Veg Mexican Sizzler",
    item_cty: "Sizzlers",
    item_subcty: "Mexican",
    item_price: 300,
    isveg: true,
    availability: true,
    item_img: "placeholder_sizzler.jpg",
  },
  // Sizzlers - Non Veg
  {
    item_id: "SZ004",
    item_name: "Chicken Chinese Sizzler",
    item_cty: "Sizzlers",
    item_subcty: "Chinese",
    item_price: 350,
    isveg: false,
    availability: true,
    item_img: "placeholder_sizzler.jpg",
  },
  {
    item_id: "SZ005",
    item_name: "Chicken Continental Sizzler",
    item_cty: "Sizzlers",
    item_subcty: "Continental",
    item_price: 350,
    isveg: false,
    availability: true,
    item_img: "placeholder_sizzler.jpg",
  },
  {
    item_id: "SZ006",
    item_name: "Chicken Mexican Sizzler",
    item_cty: "Sizzlers",
    item_subcty: "Mexican",
    item_price: 350,
    isveg: false,
    availability: true,
    item_img: "placeholder_sizzler.jpg",
  },
  // SUNDAY BRUNCH - Combos (handling as individual items for simplicity, or you could model 'combos' differently)
  // Malabar Combo Veg
  {
    item_id: "SB001",
    item_name: "Paneer Chettinad",
    item_cty: "Sunday Brunch",
    item_subcty: "Malabar Combo",
    item_price: 250,
    isveg: true,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // Malabar Combo Non-Veg
  {
    item_id: "SB002",
    item_name: "Chicken Chettinad",
    item_cty: "Sunday Brunch",
    item_subcty: "Malabar Combo",
    item_price: 275,
    isveg: false,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // Kolhapuri Combo Veg
  {
    item_id: "SB003",
    item_name: "Paneer Kolhapuri",
    item_cty: "Sunday Brunch",
    item_subcty: "Kolhapuri Combo",
    item_price: 275,
    isveg: true,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // Kolhapuri Combo Non-Veg
  {
    item_id: "SB004",
    item_name: "Mutton Kolhapuri",
    item_cty: "Sunday Brunch",
    item_subcty: "Kolhapuri Combo",
    item_price: 300,
    isveg: false,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // Amritsari Combo Veg (Paneer/Aloo)
  {
    item_id: "SB005",
    item_name: "Paneer/Aloo Kulcha",
    item_cty: "Sunday Brunch",
    item_subcty: "Amritsari Combo",
    item_price: 275, // Assuming same price for Paneer/Aloo
    isveg: true,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // Amritsari Combo Non-Veg
  {
    item_id: "SB006",
    item_name: "Mutton Kulcha",
    item_cty: "Sunday Brunch",
    item_subcty: "Amritsari Combo",
    item_price: 300,
    isveg: false,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // Continental Combo Veg
  {
    item_id: "SB007",
    item_name:"Paneer Lebanese Roll, Crispy Veggie Burger",
    item_cty: "Sunday Brunch",
    item_subcty: "Continental Combo",
    item_price: 250,
    isveg: true,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // Continental Combo Non-Veg
  {
    item_id: "SB008",
    item_name:"Chicken Lebanese Roll, Chicken Burger",
    item_cty: "Sunday Brunch",
    item_subcty: "Continental Combo",
    item_price: 275,
    isveg: false,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // Rajasthani Combo Veg
  {
    item_id: "SB009",
    item_name: "Dal, Bati, Gatta, Churma",
    item_cty: "Sunday Brunch",
    item_subcty: "Rajasthani Combo",
    item_price: 200,
    isveg: true,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // Rajasthani Combo Non-Veg
  {
    item_id: "SB010",
    item_name: "Dal, Bati, Lal Maans, Churma",
    item_cty: "Sunday Brunch",
    item_subcty: "Rajasthani Combo",
    item_price: 225,
    isveg: false,
    availability: true,
    item_img: "placeholder_brunch.jpg",
  },
  // DESSERTS
  {
    item_id: "DS001",
    item_name: "Gulab Jamun",
    item_cty: "Desserts",
    item_subcty: "Indian Sweets",
    item_price: 70,
    isveg: true,
    availability: true,
    item_img: "placeholder_dessert.jpg",
  },
  {
    item_id: "DS002",
    item_name: "Rabdi Kheer",
    item_cty: "Desserts",
    item_subcty: "Indian Sweets",
    item_price: 120,
    isveg: true,
    availability: true,
    item_img: "placeholder_dessert.jpg",
  },
  {
    item_id: "DS003",
    item_name: "Chocolate Mousse",
    item_cty: "Desserts",
    item_subcty: "Continental",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "placeholder_dessert.jpg",
  },
  {
    item_id: "DS004",
    item_name: "Fruit Cream",
    item_cty: "Desserts",
    item_subcty: "Continental",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "placeholder_dessert.jpg",
  },
  // Ice-creams (Amul) - Example, add all as needed
  {
    item_id: "IC001",
    item_name: "Rasgulla Kulfi",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC002",
    item_name: "Rajbhog Kulfi",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 30,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC003",
    item_name: "Pista Kulfi",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 30,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC004",
    item_name: "Kashmiri Kulfi",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC005",
    item_name: "Rajasthani Kulfi",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC006",
    item_name: "Bombay Kulfi",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 25,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC007",
    item_name: "Kaju Malai Kulfi",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC008",
    item_name: "Mawa Kulfi",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 25,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC009",
    item_name: "Badshah Kulfi",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 25,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC010",
    item_name: "Chocobar",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC011",
    item_name: "Frostick",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 40,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC012",
    item_name: "Coffee Bar",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC013",
    item_name: "Mango Duet",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC014",
    item_name: "Choco Vanilla",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 30,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC015",
    item_name: "Black Chocolate",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 45,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC016",
    item_name: "Butter Scotch",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 35,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC017",
    item_name: "Crunch Delight",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 25,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC018",
    item_name: "Black Currant",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 30,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC019",
    item_name: "Two in One",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 25,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC020",
    item_name: "Vanilla (Family pack)",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 230,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC021",
    item_name: "Alphanso Mango (Family pack)",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 250,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },
  {
    item_id: "IC022",
    item_name: "Butterscotch (Family pack)",
    item_cty: "Desserts",
    item_subcty: "Ice-creams (Amul)",
    item_price: 270,
    isveg: true,
    availability: true,
    item_img: "placeholder_icecream.jpg",
  },

  // DRINKS - From Images
  // Mocktails (WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg)
  {
    item_id: "DR001",
    item_name: "Mojito Madness (Mocktail)",
    item_cty: "Drinks",
    item_subcty: "Mocktails",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR002",
    item_name: "Raw Mango (Mocktail)",
    item_cty: "Drinks",
    item_subcty: "Mocktails",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR003",
    item_name: "Blue Lagoon (Mocktail)",
    item_cty: "Drinks",
    item_subcty: "Mocktails",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR004",
    item_name: "Pina Colada (Mocktail)",
    item_cty: "Drinks",
    item_subcty: "Mocktails",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR005",
    item_name: "Kiwi Punch (Mocktail)",
    item_cty: "Drinks",
    item_subcty: "Mocktails",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR006",
    item_name: "Strawberry Smash (Mocktail)",
    item_cty: "Drinks",
    item_subcty: "Mocktails",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  // Cocktails (WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg)
  {
    item_id: "DR007",
    item_name: "Mojito Madness (Cocktail)",
    item_cty: "Bar", // Updated
    item_subcty: "Cocktails",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR008",
    item_name: "Raw Mango (Cocktail)",
    item_cty: "Bar", // Updated
    item_subcty: "Cocktails",
    item_price: 140,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR009",
    item_name: "Blue Lagoon (Cocktail)",
    item_cty: "Bar", // Updated
    item_subcty: "Cocktails",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR010",
    item_name: "Pina Colada (Cocktail)",
    item_cty: "Bar", // Updated
    item_subcty: "Cocktails",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR011",
    item_name: "Kiwi Punch (Cocktail)",
    item_cty: "Bar", // Updated
    item_subcty: "Cocktails",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR012",
    item_name: "Strawberry Smash (Cocktail)",
    item_cty: "Bar", // Updated
    item_subcty: "Cocktails",
    item_price: 150,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR013",
    item_name: "Gimlet",
    item_cty: "Bar", // Updated
    item_subcty: "Cocktails",
    item_price: 140,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  {
    item_id: "DR014",
    item_name: "Long Island Ice Tea",
    item_cty: "Bar", // Updated
    item_subcty: "Cocktails",
    item_price: 260,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_535cda99.jpg",
  },
  // Beer Menu (WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg)
  {
    item_id: "DR015",
    item_name: "Bira White (330ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 84,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  {
    item_id: "DR016",
    item_name: "Bira White (500ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 115,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  {
    item_id: "DR017",
    item_name: "Corona Extra (330ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 200,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  {
    item_id: "DR018",
    item_name: "Hoegaarden (330ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 200,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  {
    item_id: "DR019",
    item_name: "Kingfisher Premium (500ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 60,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  {
    item_id: "DR020",
    item_name: "Kingfisher Strong (500ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 65,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  {
    item_id: "DR021",
    item_name: "Budwiser Premium (500ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 70,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  {
    item_id: "DR022",
    item_name: "Budwiser Magnum (500ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 90,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  {
    item_id: "DR023",
    item_name: "Breezer Cranberry (275ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 75,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  {
    item_id: "DR024",
    item_name: "Breezer Jamaican (275ML)",
    item_cty: "Bar", // Updated
    item_subcty: "Beer",
    item_price: 75,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_5f734b8f.jpg",
  },
  // Bar Menu - Alcoholic (WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg)
  {
    item_id: "DR025",
    item_name: "100 Pipers (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Whisky",
    item_price: 50,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR026",
    item_name: "Black Dog (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Whisky",
    item_price: 55,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR027",
    item_name: "Teachers (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Whisky",
    item_price: 55,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR028",
    item_name: "Vat 69 (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Whisky",
    item_price: 48,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR029",
    item_name: "Blenders Pride (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Whisky",
    item_price: 27,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR030",
    item_name: "Amrut (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Whisky",
    item_price: 103,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR031",
    item_name: "Amrut Fusion (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Whisky",
    item_price: 121,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR032",
    item_name: "Black And White (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Whisky",
    item_price: 50,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR033",
    item_name: "Smirnoff (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Vodka",
    item_price: 25,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR034",
    item_name: "Smirnoff Green Apple (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Vodka",
    item_price: 28,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR035",
    item_name: "Old Monk (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Rum",
    item_price: 17,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR036",
    item_name: "Bacardi Lemon (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Rum",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR037",
    item_name: "Morpheus (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Brandy",
    item_price: 25,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR038",
    item_name: "Red Wine (Sula/Zinfandel) (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Wine",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR039",
    item_name: "Gin London Dry (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Gin",
    item_price: 36,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR040",
    item_name: "Gin Revolution (30 ml)",
    item_cty: "Bar", // Updated
    item_subcty: "Gin",
    item_price: 25,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  // Bar Menu - Non-Alcoholic (WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg)
  {
    item_id: "DR041",
    item_name: "Juice (200 ml)",
    item_cty: "Drinks",
    item_subcty: "Juice",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR042",
    item_name: "Soft Drink (400 ml)",
    item_cty: "Drinks",
    item_subcty: "Soft Drinks",
    item_price: 20,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR043",
    item_name: "Soft Drink (330 ml)",
    item_cty: "Drinks",
    item_subcty: "Soft Drinks",
    item_price: 10,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR044",
    item_name: "Soft Drink (1 ltr)",
    item_cty: "Drinks",
    item_subcty: "Soft Drinks",
    item_price: 65,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
  {
    item_id: "DR045",
    item_name: "Soda (2.5 ltr)", // Assuming Soda, could be a large soft drink bottle
    item_cty: "Drinks",
    item_subcty: "Soft Drinks",
    item_price: 100,
    isveg: true,
    availability: true,
    item_img: "WhatsApp Image 2025-05-10 at 19.37.18_c83bb1be.jpg",
  },
];

async function populateDatabase() {
  try {
    await mongoose.connect(dbURL, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("Connected to MongoDB");

    await Menu.deleteMany({});
    console.log('Existing menu data cleared');

    await Menu.insertMany(menuData);
    console.log("Menu data inserted successfully");

    await mongoose.connection.close();
    console.log("Connection closed");
  } catch (error) {
    console.error("Error populating database:", error);
    if (mongoose.connection.readyState === 1) {
      // 1 means connected
      await mongoose.connection.close();
      console.log("Connection closed due to error.");
    }
  }
}

populateDatabase(); 
